# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --ECG-Project > environment.yml
#    conda env remove --name ECG-Project
#    conda env list

name: ECG-Project
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - bottleneck
  - mne
  - pyedflib
  - pyarrow
  - fastparquet
  - pytorch
  - torchvision
  - torchaudio
  - torchinfo
  - pip:
      - numpy==1.23.5
      - pandas==1.5.3
      - ipykernel==6.17.1
      - ipython==8.7.0
      - jupyter-client==7.4.7
      - jupyter-core==5.1.0
      - matplotlib==3.7.1
      - neurokit2==0.2.0
      - python-dotenv
      - pytest
      - pylint
      - tensorflow
      - mlflow
      - mlflow[extras]
      - mlserver
      - mlserver-mlflow
      - packaging
      - setuptools
      - evidently
      - keras
      - scikit-learn
      - seaborn
      - jax
      - jax[cpu]
      - jaxlib
      - tqdm
      - metaflow
      - metaflow-card-html
      - torcheval
      - tslearn
      - torchmetrics